apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacherapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teacherapp
  template:
    metadata:
      labels:
        app: teacherapp
    spec:
      containers:
      - name: teacherapp
        image: ccaacr001.azurecr.io/ccaacr001:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 10000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teacherapp
    k8s-app: teacherapp
  name: teacherapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 10000
  type: LoadBalancer
  selector:
    app: teacherapp
